# Generated by Django 4.2.6 on 2023-10-18 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='publications.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.SmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2023)])),
            ],
        ),
        migrations.CreateModel(
            name='PublicationName',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField()),
                ('age_rating', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)])),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ManyToManyField(related_name='publication_names', to='publications.author')),
                ('genre', models.ManyToManyField(related_name='publication_names', to='publications.genre')),
                ('year', models.ManyToManyField(related_name='publication_names', to='publications.year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='publications.country'),
        ),
    ]
